version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    expose:
      - "8000"
    ports:
      - "8000:8000"
    links:
      - postgres
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - ./local.env
    ports:
      - "5432:5432"
