# Generated by Django 2.1.10 on 2020-05-05 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('P', 'pending'), ('W', 'working'), ('C', 'completed')], default='P', max_length=2)),
                ('withdrawal', models.DateTimeField()),
                ('address', models.CharField(max_length=25)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.UserInformation')),
                ('pizza', models.ManyToManyField(to='Menu.Pizza')),
            ],
        ),
    ]
